on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: '24.0'
          elixir-version: '1.12'
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix credo
      - run: mix dialyzer
      - run: mix test
